#!/usr/bin/env bash

# Changes for SnappyData data platform.
#
# Portions Copyright (c) 2017 SnappyData, Inc. All rights reserved.
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# !! DO NOT EDIT THIS FILE. IT MAY RESULT MALFUNCTIONING OF snappy-ec2 SCRIPT !!

# These variables are automatically filled in by the snappy-ec2 script.
export LOCATORS="{{locator_list}}"
export LEADS="{{lead_list}}"
export SERVERS="{{server_list}}"
export LOCATOR_PRIVATE_IPS="{{locator_private_ips}}"
export LEAD_PRIVATE_IPS="{{lead_private_ips}}"
export SERVER_PRIVATE_IPS="{{server_private_ips}}"
export ZEPPELIN_HOST="{{zeppelin_server}}"
export SNAPPYDATA_VERSION="{{snappydata_version}}"
export AWS_ACCESS_KEY_ID="{{aws_access_key_id}}"
export AWS_SECRET_ACCESS_KEY="{{aws_secret_access_key}}"
export LOCATOR_CLIENT_PORT="{{locator_client_port}}"
export SNAPPYDATA_TARBALL_URL="{{snappydata-tarball-url}}"
export PRIVATE_BUILD_PATH="{{private_build_path}}"
export LOCATOR_CONF="{{locator_conf}}"
export SERVER_CONF="{{server_conf}}"
export LEAD_CONF="{{lead_conf}}"
export INTERPRETER_VERSION="0.7.3.2"
export SNAPPY_HOME_DIR="/opt/snappydata"
